LORA_R = 128
LORA_ALPHA = 128
LORA_DROPOUT = 0.15
LORA_TARGET_MODULES = ["q_proj", "k_proj", "v_proj"]
LORA_BIAS = "none"
USE_DORA=False
USE_RSLORA=False

LEARNING_RATE = 5e-05
BATCH_SIZE = 2
GRAD_ACCUM = 4
EPOCHS = 5

WEIGHT_DECAY = 0.03
WARMUP_RATIO = 0.15
LR_SCHEDULER = "cosine"

LOGGING_STEPS = 10
EVAL_STEPS = 400
